### ISSUE TITLE
nc: unix connect failed: Connection refused

### ISSUE THREAD

**Issue by aeshaynes** [prawnsalad/IRCD-Balancer#2]
executing nc -U /opt/ircdbalancer/control.sock causes
`nc: unix connect failed: Permission denied`

and also when run with sudo produces
`nc: unix connect failed: Connection refused`

**Comment by pradeshc** [comment]
You need to have a listener first

So first open a listing socket 
nc -lU /opt/ircdbalancer/control.sock

Then write 
/opt/ircdbalancer/somecommand_with_output | nc -U /opt/ircdbalancer/control.sock
